spring.datasource.url=jdbc:mariadb://localhost:3306/secure_user_api
spring.datasource.username=root
spring.datasource.password=user1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# application.properties
jwt.secret=8f3a92c1e6d4b7f0a5c8e1d4b7f0a3c6e9d2b5f8a1c4e7d0b3f6a9c2e5d8b1f4
jwt.expiration=3600000
jwt.refresh-expiration=604800000